"""Centralized display labels for analytics fields."""

DISPLAY_LABELS = {
    "id_rumah_sakit": "ID rumah sakit",
    "nama_rumah_sakit": "Rumah sakit",
    "provinsi": "Provinsi",
    "kelas_rumah_sakit": "Kelas",
    "kepemilikan": "Kepemilikan",
    "jumlah_tempat_tidur": "Tempat tidur",
    "jumlah_jenis_layanan": "Jenis layanan",
    "skor_kematangan_digital": "Kematangan Digital",
    "expected_digital_maturity_oof": "Kematangan Digital Ekspektasian",
    "digital_conversion_gap": "Kesenjangan Konversi Digital",
    "investment_intensity_score": "Intensitas Investasi IT",
    "anggaran_it_per_bed": "Anggaran IT per Tempat Tidur",
    "staf_it_per_100_bed": "Staf IT per 100 Tempat Tidur",
    "iot_per_100_bed": "Perangkat IoT per 100 Tempat Tidur",
    "telemedicine_rate_per_1000": "Telemedicine per 1.000 Kunjungan",
    "tingkat_keterisian_tempat_tidur_persen": "BOR",
    "rata_rata_lama_rawat_hari": "Rata-rata LOS",
    "rata_rata_waktu_respons_rujukan_menit": "Waktu Respons Rujukan",
    "operational_burden_score": "Beban Operasional",
    "digital_deficit_score": "Defisit Digital",
    "investment_underperformance_score": "Underperformance Investasi",
    "intervention_priority_score": "Skor Prioritas",
    "priority_rank": "Peringkat",
    "intervention_tier": "Tier Intervensi",
    "root_cause_primary": "Hambatan Dominan",
    "recommended_intervention": "Intervensi yang Direkomendasikan",
}
